// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// dotenv/config defaults to loading .env from the current working
// directory - but the real .env lives at the repo root (one level up from
// backend/), not inside backend/ itself, so it must be pointed there
// explicitly regardless of where this CLI is invoked from.
import { config } from "dotenv";
config({ path: "../.env" });
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
